import mongoose from 'mongoose';

const websiteSettingSchema = new mongoose.Schema({
  siteName: { type: String, default: 'BlogHub' },
  siteTitle: { type: String, default: '' },
  siteDescription: { type: String, default: '' },
  logo: { type: String, default: '' },
  logoWidth: { type: String, default: '' },
  logoHeight: { type: String, default: '40' },
  logoBorderRadius: { type: String, default: '0' },
  favicon: { type: String, default: '' },
  socialLinks: {
    facebook: { type: String, default: '' },
    twitter: { type: String, default: '' },
    instagram: { type: String, default: '' },
    linkedin: { type: String, default: '' },
    youtube: { type: String, default: '' },
  },
  contactEmail: { type: String, default: '' },
  contactPhone: { type: String, default: '' },
  contactAddress: { type: String, default: '' },
  aboutUs: { type: String, default: '' },
  termsAndConditions: { type: String, default: '' },
  privacyPolicy: { type: String, default: '' },
  footerText: { type: String, default: '' },
  theme: {
    preset: { type: String, default: 'default' },
    light: {
      primary: { type: String, default: '#0D9488' },
      secondary: { type: String, default: '#6366F1' },
      background: { type: String, default: '#F8FAFC' },
      surface: { type: String, default: '#FFFFFF' },
      text: { type: String, default: '#1E293B' },
      textSecondary: { type: String, default: '#64748B' },
      heading: { type: String, default: '#0F172A' },
      link: { type: String, default: '#2563EB' },
      linkHover: { type: String, default: '#1D4ED8' },
      border: { type: String, default: '#E2E8F0' },
      buttonPrimary: { type: String, default: '#0D9488' },
      buttonPrimaryHover: { type: String, default: '#0F766E' },
      buttonPrimaryText: { type: String, default: '#FFFFFF' },
      buttonSecondary: { type: String, default: '#6366F1' },
      buttonSecondaryHover: { type: String, default: '#4F46E5' },
      buttonSecondaryText: { type: String, default: '#FFFFFF' },
      headerBg: { type: String, default: '#FFFFFF' },
      headerText: { type: String, default: '#1E293B' },
      footerBg: { type: String, default: '#0F172A' },
      footerText: { type: String, default: '#CBD5E1' },
      accent: { type: String, default: '#F59E0B' },
      success: { type: String, default: '#10B981' },
      error: { type: String, default: '#EF4444' },
      warning: { type: String, default: '#F59E0B' },
    },
    dark: {
      primary: { type: String, default: '#F43F5E' },
      secondary: { type: String, default: '#A855F7' },
      background: { type: String, default: '#0F0F1A' },
      surface: { type: String, default: '#1A1A2E' },
      text: { type: String, default: '#F1F5F9' },
      textSecondary: { type: String, default: '#94A3B8' },
      heading: { type: String, default: '#F8FAFC' },
      link: { type: String, default: '#60A5FA' },
      linkHover: { type: String, default: '#93C5FD' },
      border: { type: String, default: '#334155' },
      buttonPrimary: { type: String, default: '#F43F5E' },
      buttonPrimaryHover: { type: String, default: '#E11D48' },
      buttonPrimaryText: { type: String, default: '#FFFFFF' },
      buttonSecondary: { type: String, default: '#A855F7' },
      buttonSecondaryHover: { type: String, default: '#9333EA' },
      buttonSecondaryText: { type: String, default: '#FFFFFF' },
      headerBg: { type: String, default: '#1A1A2E' },
      headerText: { type: String, default: '#F1F5F9' },
      footerBg: { type: String, default: '#0F0F1A' },
      footerText: { type: String, default: '#94A3B8' },
      accent: { type: String, default: '#FBBF24' },
      success: { type: String, default: '#34D399' },
      error: { type: String, default: '#F87171' },
      warning: { type: String, default: '#FBBF24' },
    },
  },
}, { timestamps: true });

export default mongoose.model('WebsiteSetting', websiteSettingSchema);
